import type { OrderData } from '../types';

export const mockOrderData: OrderData[] = [
  {
    id: '#CM9801',
    user: { name: 'Natali Craig', avatar: '/src/assets/images/Female05.png' },
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: '2024-09-20',
    dateLabel: 'Just now',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9802',
    user: { name: 'Kate Morrison', avatar: '/src/assets/images/Female05.png' },
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: '2024-09-20',
    dateLabel: 'A minute ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9803',
    user: { name: 'Drew Cano', avatar: '/src/assets/images/Male06.png' },
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '2024-09-20',
    dateLabel: '1 hour ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9804',
    user: { name: 'Orlando Diggs', avatar: '/src/assets/images/Male07.png' },
    project: 'Admin Dashboard',
    address: 'Washburn Baton Rouge',
    date: '2024-09-19',
    dateLabel: 'Yesterday',
    status: 'Approved',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9805',
    user: { name: 'Andi Lane', avatar: '/src/assets/images/Male08.png' },
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: '2024-02-02',
    dateLabel: 'Feb 2, 2023',
    status: 'Rejected',
    showCheckbox: true,
    showMoreVert: true,
    shoClipboardText: true,
  },
  {
    id: '#CM9806',
    user: { name: 'Natali Craig', avatar: '/src/assets/images/Female05.png' },
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: '2024-09-20',
    dateLabel: 'Just now',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9807',
    user: { name: 'Kate Morrison', avatar: '/src/assets/images/Female05.png' },
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: '2024-09-20',
    dateLabel: 'A minute ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9808',
    user: { name: 'Drew Cano', avatar: '/src/assets/images/Male06.png' },
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '2024-09-20',
    dateLabel: '1 hour ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9809',
    user: { name: 'Orlando Diggs', avatar: '/src/assets/images/Male07.png' },
    project: 'Admin Dashboard',
    address: 'Washburn Baton Rouge',
    date: '2024-09-19',
    dateLabel: 'Yesterday',
    status: 'Approved',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9810',
    user: { name: 'Andi Lane', avatar: '/src/assets/images/Male08.png' },
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: '2024-02-02',
    dateLabel: 'Feb 2, 2023',
    status: 'Rejected',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9811',
    user: { name: 'Sarah Johnson', avatar: '/src/assets/images/Female05.png' },
    project: 'E-commerce Site',
    address: 'Park Avenue New York',
    date: '2024-09-18',
    dateLabel: '3 days ago',
    status: 'In Progress',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9812',
    user: { name: 'Michael Brown', avatar: '/src/assets/images/Male06.png' },
    project: 'Mobile App',
    address: 'Silicon Valley California',
    date: '2024-09-17',
    dateLabel: '4 days ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: true,
  },
  // Adding 50 more entries
  {
    id: '#CM9813',
    user: { name: 'Emma Wilson', avatar: '/src/assets/images/3D03.png' },
    project: 'Portfolio Website',
    address: 'Broadway Street Seattle',
    date: '2024-09-16',
    dateLabel: '5 days ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9814',
    user: { name: 'James Rodriguez', avatar: '/src/assets/images/Male11.png' },
    project: 'SaaS Dashboard',
    address: 'Main Street Austin',
    date: '2024-09-15',
    dateLabel: '6 days ago',
    status: 'Approved',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9815',
    user: { name: 'Olivia Davis', avatar: '/src/assets/images/3D05.png' },
    project: 'Blog Platform',
    address: 'Ocean Drive Miami',
    date: '2024-09-14',
    dateLabel: '1 week ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9816',
    user: { name: 'Liam Garcia', avatar: '/src/assets/images/Male07.png' },
    project: 'Inventory System',
    address: 'Commerce Street Dallas',
    date: '2024-09-13',
    dateLabel: '1 week ago',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9817',
    user: { name: 'Sophia Martinez', avatar: '/src/assets/images/3D08.png' },
    project: 'Learning Management',
    address: 'University Avenue Denver',
    date: '2024-09-12',
    dateLabel: '1 week ago',
    status: 'Rejected',
    showCheckbox: true,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9818',
    user: { name: 'Noah Anderson', avatar: '/src/assets/images/Male06.png' },
    project: 'Task Manager',
    address: 'Tech Boulevard Phoenix',
    date: '2024-09-11',
    dateLabel: '2 weeks ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9819',
    user: { name: 'Isabella Taylor', avatar: '/src/assets/images/Female05.png' },
    project: 'Social Media App',
    address: 'Innovation Drive Portland',
    date: '2024-09-10',
    dateLabel: '2 weeks ago',
    status: 'Approved',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9820',
    user: { name: 'Mason Thomas', avatar: '/src/assets/images/Male08.png' },
    project: 'Video Streaming',
    address: 'Media Street Los Angeles',
    date: '2024-09-09',
    dateLabel: '2 weeks ago',
    status: 'Complete',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9821',
    user: { name: 'Ava Jackson', avatar: '/src/assets/images/3D03.png' },
    project: 'Food Delivery App',
    address: 'Restaurant Row Chicago',
    date: '2024-09-08',
    dateLabel: '2 weeks ago',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9822',
    user: { name: 'Ethan White', avatar: '/src/assets/images/Male11.png' },
    project: 'Fitness Tracker',
    address: 'Health Plaza Boston',
    date: '2024-09-07',
    dateLabel: '2 weeks ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9823',
    user: { name: 'Charlotte Harris', avatar: '/src/assets/images/3D05.png' },
    project: 'Real Estate Portal',
    address: 'Property Lane Nashville',
    date: '2024-09-06',
    dateLabel: '3 weeks ago',
    status: 'Rejected',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9824',
    user: { name: 'Alexander Clark', avatar: '/src/assets/images/Male07.png' },
    project: 'Banking Dashboard',
    address: 'Financial District New York',
    date: '2024-09-05',
    dateLabel: '3 weeks ago',
    status: 'Approved',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9825',
    user: { name: 'Amelia Lewis', avatar: '/src/assets/images/3D08.png' },
    project: 'Travel Booking',
    address: 'Airport Boulevard Orlando',
    date: '2024-09-04',
    dateLabel: '3 weeks ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9826',
    user: { name: 'Benjamin Robinson', avatar: '/src/assets/images/Male06.png' },
    project: 'Music Streaming',
    address: 'Sound Avenue Nashville',
    date: '2024-09-03',
    dateLabel: '3 weeks ago',
    status: 'In Progress',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9827',
    user: { name: 'Harper Walker', avatar: '/src/assets/images/Female05.png' },
    project: 'News Platform',
    address: 'Media Center Atlanta',
    date: '2024-09-02',
    dateLabel: '3 weeks ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9828',
    user: { name: 'Lucas Young', avatar: '/src/assets/images/Male08.png' },
    project: 'Weather App',
    address: 'Climate Street Tampa',
    date: '2024-09-01',
    dateLabel: '3 weeks ago',
    status: 'Approved',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9829',
    user: { name: 'Evelyn Allen', avatar: '/src/assets/images/3D03.png' },
    project: 'Recipe Sharing',
    address: 'Culinary Avenue San Diego',
    date: '2024-08-31',
    dateLabel: '1 month ago',
    status: 'Complete',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9830',
    user: { name: 'Henry King', avatar: '/src/assets/images/Male11.png' },
    project: 'Gaming Platform',
    address: 'Entertainment District Las Vegas',
    date: '2024-08-30',
    dateLabel: '1 month ago',
    status: 'Rejected',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9831',
    user: { name: 'Abigail Wright', avatar: '/src/assets/images/3D05.png' },
    project: 'Pet Care App',
    address: 'Animal Shelter Road Detroit',
    date: '2024-08-29',
    dateLabel: '1 month ago',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9832',
    user: { name: 'William Lopez', avatar: '/src/assets/images/Male07.png' },
    project: 'Car Rental System',
    address: 'Auto Mall Sacramento',
    date: '2024-08-28',
    dateLabel: '1 month ago',
    status: 'Pending',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9833',
    user: { name: 'Emily Hill', avatar: '/src/assets/images/3D08.png' },
    project: 'Event Management',
    address: 'Convention Center Houston',
    date: '2024-08-27',
    dateLabel: '1 month ago',
    status: 'Approved',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9834',
    user: { name: 'James Scott', avatar: '/src/assets/images/Male06.png' },
    project: 'Appointment Booking',
    address: 'Medical Plaza Minneapolis',
    date: '2024-08-26',
    dateLabel: '1 month ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9835',
    user: { name: 'Victoria Green', avatar: '/src/assets/images/Female05.png' },
    project: 'Document Scanner',
    address: 'Office Park Cleveland',
    date: '2024-08-25',
    dateLabel: '1 month ago',
    status: 'In Progress',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9836',
    user: { name: 'Daniel Adams', avatar: '/src/assets/images/Male08.png' },
    project: 'Password Manager',
    address: 'Security Boulevard San Antonio',
    date: '2024-08-24',
    dateLabel: '1 month ago',
    status: 'Rejected',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9837',
    user: { name: 'Grace Baker', avatar: '/src/assets/images/3D03.png' },
    project: 'Language Learning',
    address: 'Education Street Philadelphia',
    date: '2024-08-23',
    dateLabel: '1 month ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9838',
    user: { name: 'Matthew Nelson', avatar: '/src/assets/images/Male11.png' },
    project: 'Stock Trading App',
    address: 'Wall Street New York',
    date: '2024-08-22',
    dateLabel: '1 month ago',
    status: 'Approved',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9839',
    user: { name: 'Chloe Carter', avatar: '/src/assets/images/3D05.png' },
    project: 'Virtual Reality Game',
    address: 'Tech Campus Palo Alto',
    date: '2024-08-21',
    dateLabel: '1 month ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9840',
    user: { name: 'Joseph Mitchell', avatar: '/src/assets/images/Male07.png' },
    project: 'Cryptocurrency Wallet',
    address: 'Blockchain Avenue Austin',
    date: '2024-08-20',
    dateLabel: '1 month ago',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9841',
    user: { name: 'Zoe Perez', avatar: '/src/assets/images/3D08.png' },
    project: 'IoT Dashboard',
    address: 'Smart City Drive Charlotte',
    date: '2024-08-19',
    dateLabel: '5 weeks ago',
    status: 'Pending',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9842',
    user: { name: 'Christopher Roberts', avatar: '/src/assets/images/Male06.png' },
    project: 'AI Chatbot',
    address: 'AI Research Lab Boston',
    date: '2024-08-18',
    dateLabel: '5 weeks ago',
    status: 'Rejected',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9843',
    user: { name: 'Lily Turner', avatar: '/src/assets/images/Female05.png' },
    project: 'Meditation App',
    address: 'Wellness Center Portland',
    date: '2024-08-17',
    dateLabel: '5 weeks ago',
    status: 'Approved',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9844',
    user: { name: 'David Phillips', avatar: '/src/assets/images/Male08.png' },
    project: 'Delivery Tracking',
    address: 'Logistics Hub Memphis',
    date: '2024-08-16',
    dateLabel: '5 weeks ago',
    status: 'Complete',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9845',
    user: { name: 'Aria Campbell', avatar: '/src/assets/images/3D03.png' },
    project: 'Photo Editor',
    address: 'Creative District San Francisco',
    date: '2024-08-15',
    dateLabel: '5 weeks ago',
    status: 'In Progress',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9846',
    user: { name: 'Anthony Parker', avatar: '/src/assets/images/Male11.png' },
    project: 'Voice Assistant',
    address: 'Tech Valley Seattle',
    date: '2024-08-14',
    dateLabel: '5 weeks ago',
    status: 'Pending',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9847',
    user: { name: 'Nora Evans', avatar: '/src/assets/images/3D05.png' },
    project: 'Smart Home Control',
    address: 'Innovation Park Denver',
    date: '2024-08-13',
    dateLabel: '6 weeks ago',
    status: 'Approved',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
  {
    id: '#CM9848',
    user: { name: 'Joshua Edwards', avatar: '/src/assets/images/Male07.png' },
    project: 'Expense Tracker',
    address: 'Finance District Chicago',
    date: '2024-08-12',
    dateLabel: '6 weeks ago',
    status: 'Complete',
    showCheckbox: false,
    showMoreVert: true,
    shoClipboardText: false,
  },
  {
    id: '#CM9849',
    user: { name: 'Hazel Collins', avatar: '/src/assets/images/3D08.png' },
    project: 'Online Marketplace',
    address: 'Commerce Center Miami',
    date: '2024-08-11',
    dateLabel: '6 weeks ago',
    status: 'Rejected',
    showCheckbox: false,
    showMoreVert: false,
    shoClipboardText: true,
  },
  {
    id: '#CM9850',
    user: { name: 'Andrew Stewart', avatar: '/src/assets/images/Male06.png' },
    project: 'Video Conference',
    address: 'Communication Hub Austin',
    date: '2024-08-10',
    dateLabel: '6 weeks ago',
    status: 'In Progress',
    showCheckbox: true,
    showMoreVert: false,
    shoClipboardText: false,
  },
 
];

